# Analysis

In [1]:
%%sql
SELECT * FROM mock_data
LIMIT 50

,id,external_id,customer_inner_id,customer_first_name,customer_last_name,customer_age,customer_email,customer_country,customer_postal_code,customer_pet_inner_id,...,product_release_date,product_expiry_date,supplier_inner_id,supplier_name,supplier_contact,supplier_email,supplier_phone,supplier_address,supplier_city,supplier_country
0,1,1,1,Barron,Rawlyns,61,bmassingham0@army.mil,China,NaN,NaN,...,2011-10-19,2028-10-21,1,Tagcat,Bevan Massingham,bmassingham0@unblog.fr,914-877-7062,Suite 25,Kletek,China
1,2,2,2,Ham,Knowller,78,cscudder1@time.com,Poland,73-115,NaN,...,2019-04-17,2028-02-29,2,Livetube,Candide Scudder,cscudder1@sbwire.com,863-319-5653,18th Floor,Santa Cruz Balanyá,Poland
2,3,3,3,Farleigh,Langley,71,vhuxter2@fotki.com,Poland,56-160,NaN,...,2010-02-03,2023-09-03,3,Photobug,Vinson Huxter,vhuxter2@slate.com,434-817-1275,Apt 96,Huangpu,Samoa
3,4,4,4,Shae,Debling,28,bbullier3@bravesites.com,Sri Lanka,81700,NaN,...,2019-08-22,2026-03-29,4,Janyx,Bald Bullier,bbullier3@dot.gov,515-756-7392,12th Floor,Chengzhong,Indonesia
4,5,5,5,Lay,Twatt,25,sedgar4@smugmug.com,Botswana,NaN,NaN,...,2018-12-09,2030-05-10,5,Lazz,Sydelle Edgar,sedgar4@reverbnation.com,861-980-8811,Suite 79,Lanxi,China
5,6,6,6,Frankie,Waycott,58,dgrindell5@usa.gov,Russia,666733,NaN,...,2017-12-24,2030-07-11,6,Izio,Doria Grindell,dgrindell5@1688.com,314-270-0484,3rd Floor,Saint Louis,Russia
6,7,7,7,Boote,Ricart,69,kelies6@si.edu,Dominican Republic,11902,NaN,...,2013-08-12,2028-03-18,7,Fanoodle,Kenny Elies,kelies6@hao123.com,627-887-5660,PO Box 84390,Somorpenang,Mexico
7,8,8,8,Mace,Parkman,22,tungaretti7@census.gov,Mexico,58095,NaN,...,2015-07-23,2028-05-31,8,Thoughtblab,Tabina Ungaretti,tungaretti7@shareasale.com,325-667-3782,Room 922,Panjakent,Russia
8,9,9,9,Hobard,Rawnsley,74,mglason8@jugem.jp,China,NaN,NaN,...,2018-07-09,2025-04-30,9,Dabvine,May Glason,mglason8@so-net.ne.jp,459-716-0328,3rd Floor,Leonidovo,Philippines
9,10,10,10,Jorry,Cattenach,46,jpelerin9@cbsnews.com,Poland,34-146,NaN,...,2014-03-06,2023-05-30,10,Linktype,Jorry Pelerin,jpelerin9@theguardian.com,540-290-6958,Suite 34,Sukadami,Indonesia
10,11,11,11,Starr,Wapples,50,ecorgenvina@networkadvertising.org,France,69281 CEDEX 01,NaN,...,2013-02-09,2028-05-26,11,Livepath,Edwina Corgenvin,ecorgenvina@furl.net,670-482-8563,Suite 92,Setun’,Ukraine
11,12,12,12,Marlena,Huthart,34,btolletb@bloglines.com,Japan,839-1301,NaN,...,2015-06-03,2023-01-23,12,Tagpad,Birch Tollet,btolletb@unblog.fr,891-439-6430,Suite 92,La Paz,Peru
12,13,13,13,Eleni,Arundel,41,lkolinc@adobe.com,Canada,P3Y,NaN,...,2022-12-13,2023-08-09,13,Twitterlist,Laure Kolin,lkolinc@japanpost.jp,511-806-8348,Apt 282,Piedrancha,Canada
13,14,14,14,Vivianne,Curwen,67,ddunkersleyd@cyberchimps.com,Tanzania,NaN,NaN,...,2011-09-23,2025-02-17,14,Quatz,Daphne Dunkersley,ddunkersleyd@photobucket.com,533-667-4421,Room 1779,Shuishi,Philippines
14,15,15,15,Darrelle,Crawforth,25,mlanneye@histats.com,Sweden,448 92,NaN,...,2019-10-08,2029-07-14,15,Demimbu,Marcile Lanney,mlanneye@paginegialle.it,576-589-0332,Suite 53,Senovo,Sweden
15,16,16,16,Reeva,Seden,65,lbristoef@psu.edu,Sweden,144 62,NaN,...,2011-10-14,2023-05-12,16,Devbug,Lucinda Bristoe,lbristoef@exblog.jp,868-648-5000,1st Floor,Ashkāsham,Egypt
16,17,17,17,Urbanus,Fannin,48,rgrissg@live.com,Mexico,61609,NaN,...,2015-03-24,2030-08-08,17,Yata,Ronni Griss,rgrissg@fda.gov,661-382-9801,17th Floor,Bang Pahan,Brazil
17,18,18,18,Barnaby,Blanko,36,chellewellh@smugmug.com,Russia,143422,NaN,...,2013-09-12,2024-09-14,18,Oyoyo,Cirilo Hellewell,chellewellh@google.ca,484-944-2476,7th Floor,Manzë,Portugal
18,19,19,19,Tabbatha,Aizikovitz,55,bhalburtoni@woothemes.com,Poland,74-101,NaN,...,2011-05-20,2029-06-02,19,Fivespan,Bell Halburton,bhalburtoni@latimes.com,105-726-0281,Suite 11,‘Irbīn,Germany
19,20,20,20,Anne,Mcimmie,49,hdilkesj@dmoz.org,Brazil,80000-000,NaN,...,2015-12-20,2024-05-07,20,Blognation,Happy Dilkes,hdilkesj@clickbank.net,814-851-5183,8th Floor,Sandy Bay,Indonesia
20,21,21,21,Doris,Walsom,64,hmatevosiank@salon.com,Tanzania,NaN,NaN,...,2011-12-01,2027-12-26,21,Lazzy,Helen-elizabeth Matevosian,hmatevosiank@delicious.com,742-561-5932,Room 341,Shuibian,Philippines
21,105,105,105,Ashlee,Nibloe,38,baplin2w@businessinsider.com,Russia,636132,NaN,...,2011-02-21,2028-07-06,105,Devify,Brok Aplin,baplin2w@answers.com,614-393-5199,Room 1785,Tsagaan-Olom,Japan
22,22,22,22,Stefano,Reede,57,wtythel@elegantthemes.com,Saudi Arabia,NaN,NaN,...,2013-12-25,2027-06-08,22,Bluejam,Wendi Tythe,wtythel@list-manage.com,248-506-3333,11th Floor,Caluya,China
23,23,23,23,Gerhard,Inger,28,fboddism@theguardian.com,China,NaN,NaN,...,2019-03-26,2029-06-05,23,Roomm,Fionnula Boddis,fboddism@amazonaws.com,697-813-2372,Room 559,Mikhaylovsk,Philippines
24,24,24,24,Yorke,Elvins,66,bdobrovskyn@fc2.com,China,NaN,NaN,...,2018-02-27,2029-01-02,24,Jamia,Batsheva Dobrovsky,bdobrovskyn@pagesperso-orange.fr,895-554-4658,Suite 14,Chantilly,Brazil
25,25,25,25,Remy,McIvor,54,cwanneso@wsj.com,Cyprus,NaN,NaN,...,2016-12-01,2023-08-19,25,Skinder,Calla Wannes,cwanneso@newyorker.com,669-405-6296,Apt 100,Karanglincak,France
26,26,26,26,Emlen,Bowman,77,bmckeneyp@people.com.cn,Colombia,734007,NaN,...,2011-11-08,2024-04-11,26,Voonte,Bentlee McKeney,bmckeneyp@examiner.com,115-596-0563,Room 1468,Guazapa,Argentina
27,27,27,27,Joyce,Hofler,27,lmitchellq@amazon.com,Mongolia,NaN,NaN,...,2019-08-18,2027-07-01,27,Topicblab,Lindon Mitchell,lmitchellq@intel.com,948-598-7344,PO Box 13192,San Juan,China
28,28,28,28,Guenevere,Grugerr,54,vogianyr@tripod.com,China,NaN,NaN,...,2019-09-04,2030-02-08,28,Flashset,Von O'Giany,vogianyr@cdc.gov,671-171-4742,PO Box 26446,Novi Itebej,Czech Republic
29,29,29,29,Annadiane,Eagle,45,wwakelins@newyorker.com,Serbia,NaN,NaN,...,2011-11-28,2029-04-04,29,Tekfly,Worthington Wakelin,wwakelins@dyndns.org,967-810-0742,Suite 75,Gurupi,Portugal
30,30,30,30,Verene,Maurice,31,roccleshawt@flavors.me,Georgia,NaN,NaN,...,2013-01-25,2029-07-08,30,Thoughtworks,Rodrique Occleshaw,roccleshawt@amazon.co.jp,229-589-3541,Suite 44,Suren,Russia
31,31,31,31,Jameson,Lazer,33,msantiu@exblog.jp,Philippines,5207,NaN,...,2017-01-23,2024-12-27,31,Vipe,Marna Santi,msantiu@w3.org,513-128-8454,Apt 802,Nanger,Somalia
32,32,32,32,Deny,Frid,51,wbarajazv@tumblr.com,Colombia,855058,NaN,...,2022-10-21,2027-08-26,32,Mydo,Willette Barajaz,wbarajazv@godaddy.com,838-959-2066,Apt 195,Örebro,Indonesia
33,33,33,33,Kahaleel,Golde,41,bgwiltw@friendfeed.com,Ukraine,NaN,NaN,...,2022-05-22,2030-10-17,33,Jatri,Bertine Gwilt,bgwiltw@ox.ac.uk,694-546-3357,4th Floor,Apt,Philippines
34,34,34,34,Randall,Cheese,24,sjohannessonx@wikia.com,Philippines,6310,NaN,...,2012-08-26,2026-01-22,34,Jabbertype,Susanetta Johannesson,sjohannessonx@gnu.org,423-820-9452,Room 31,Nova Iguaçu,Brazil
35,35,35,35,Filide,Chatband,51,cpringley@hud.gov,Peru,NaN,NaN,...,2022-01-19,2027-11-03,35,Buzzbean,Curr Pringle,cpringley@harvard.edu,414-257-2547,Suite 54,Zoumi,China
36,36,36,36,Dolorita,Beagles,34,igrigautz@statcounter.com,China,NaN,NaN,...,2012-02-21,2025-11-18,36,Mynte,Isidor Grigaut,igrigautz@etsy.com,969-213-4112,Room 302,Los Cóndores,France
37,37,37,37,Olwen,Niese,52,mortas10@dyndns.org,China,NaN,NaN,...,2012-01-05,2025-01-17,37,Yombu,Marcie Ortas,mortas10@example.com,787-635-1684,Suite 3,Gobernador Ingeniero Valentín Virasoro,China
38,38,38,38,Tallulah,Clarage,67,ocostellow11@constantcontact.com,United States,80305,NaN,...,2012-07-21,2023-08-24,38,Voonyx,Olav Costellow,ocostellow11@npr.org,890-478-6782,Apt 1975,Ipauçu,Portugal
39,39,39,39,Suzy,Winning,75,cosesnane12@lycos.com,Philippines,4715,NaN,...,2010-11-17,2024-05-01,39,Mymm,Court O'Sesnane,cosesnane12@linkedin.com,941-604-7898,7th Floor,Thành Phố Hạ Long,Russia
40,40,40,40,Sonni,Barrasse,54,ayglesia13@trellian.com,Philippines,5706,NaN,...,2020-02-14,2029-03-29,40,Quinu,Alfreda Yglesia,ayglesia13@boston.com,859-783-4087,Apt 1489,Jeju-si,Thailand
41,41,41,41,Fina,McTeague,55,afullman14@forbes.com,Indonesia,NaN,NaN,...,2022-08-13,2028-04-17,41,Oyope,Anallise Fullman,afullman14@narod.ru,861-299-8062,17th Floor,Kaliterus,Philippines
42,42,42,42,Tamara,Harcombe,65,rmorecombe15@altervista.org,Bulgaria,5667,NaN,...,2011-04-12,2030-01-22,42,Zoombeat,Reece Morecombe,rmorecombe15@google.com.au,484-770-4059,Room 782,Reims,China
43,43,43,43,Maurizia,Arkin,58,qtenaunt16@samsung.com,United States,10105,NaN,...,2015-12-10,2024-12-14,43,Meemm,Quentin Tenaunt,qtenaunt16@google.es,299-242-7092,Apt 1055,Saeul,China
44,44,44,44,Tandie,Maciaszek,48,mstarton17@nifty.com,Brazil,37460-000,NaN,...,2016-05-20,2030-10-14,44,Shufflebeat,Marylee Starton,mstarton17@infoseek.co.jp,184-239-9484,Room 1564,Umuahia,Indonesia
45,45,45,45,Lefty,Weal,78,rwalisiak18@omniture.com,Czech Republic,341 92,NaN,...,2021-08-24,2027-11-02,45,Realpoint,Raddie Walisiak,rwalisiak18@nifty.com,409-877-8236,10th Floor,Álimos,Russia
46,46,46,46,Peder,Borzone,65,ksnoxall19@hexun.com,France,19117 CEDEX,NaN,...,2022-09-27,2030-05-29,46,Flipstorm,Kendall Snoxall,ksnoxall19@toplist.cz,610-357-3778,9th Floor,Banjar Lalangpasek,Indonesia
47,47,47,47,Bernard,MacFadin,75,pmallalieu1a@1und1.de,Pakistan,50470,NaN,...,2013-05-15,2023-03-12,47,Trudeo,Paolina Mallalieu,pmallalieu1a@gnu.org,807-664-5711,Room 884,Huangqi,China
48,48,48,48,Hyacinth,Egger,39,kalyutin1b@elpais.com,Japan,960-8141,NaN,...,2015-10-05,2025-07-30,48,Edgepulse,Kamila Alyutin,kalyutin1b@goo.ne.jp,298-893-0990,Suite 6,Derzhavīnsk,China
49,49,49,49,Ellyn,Sandison,65,pwhitfield1c@vk.com,Sweden,814 41,NaN,...,2021-06-06,2030-09-26,49,Youspan,Pancho Whitfield,pwhitfield1c@hexun.com,720-584-6527,Apt 582,Zvečan,Argentina

In [2]:
%%sql
# SELECT * FROM mock_data

,id,external_id,customer_inner_id,customer_first_name,customer_last_name,customer_age,customer_email,customer_country,customer_postal_code,customer_pet_inner_id,...,product_release_date,product_expiry_date,supplier_inner_id,supplier_name,supplier_contact,supplier_email,supplier_phone,supplier_address,supplier_city,supplier_country
0,1,1,1,Barron,Rawlyns,61,bmassingham0@army.mil,China,NaN,NaN,...,2011-10-19,2028-10-21,1,Tagcat,Bevan Massingham,bmassingham0@unblog.fr,914-877-7062,Suite 25,Kletek,China
1,2,2,2,Ham,Knowller,78,cscudder1@time.com,Poland,73-115,NaN,...,2019-04-17,2028-02-29,2,Livetube,Candide Scudder,cscudder1@sbwire.com,863-319-5653,18th Floor,Santa Cruz Balanyá,Poland
2,3,3,3,Farleigh,Langley,71,vhuxter2@fotki.com,Poland,56-160,NaN,...,2010-02-03,2023-09-03,3,Photobug,Vinson Huxter,vhuxter2@slate.com,434-817-1275,Apt 96,Huangpu,Samoa
3,4,4,4,Shae,Debling,28,bbullier3@bravesites.com,Sri Lanka,81700,NaN,...,2019-08-22,2026-03-29,4,Janyx,Bald Bullier,bbullier3@dot.gov,515-756-7392,12th Floor,Chengzhong,Indonesia
4,5,5,5,Lay,Twatt,25,sedgar4@smugmug.com,Botswana,NaN,NaN,...,2018-12-09,2030-05-10,5,Lazz,Sydelle Edgar,sedgar4@reverbnation.com,861-980-8811,Suite 79,Lanxi,China
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,996,9996,Perry,Edwins,49,mkardosrn@jimdo.com,Indonesia,NaN,NaN,...,2019-01-15,2024-04-09,9996,Quire,Milty Kardos,mkardosrn@barnesandnoble.com,688-242-0789,Suite 47,São Caetano do Sul,Brazil
9996,9997,997,9997,Benedick,Sherwell,71,ikingzettro@salon.com,El Salvador,NaN,NaN,...,2014-05-25,2025-08-31,9997,Eimbee,Isidora Kingzett,ikingzettro@eepurl.com,279-253-6631,Apt 79,Aoqiao,Ukraine
9997,9998,998,9998,Lombard,Oxtarby,42,sdrakeleyrp@bluehost.com,Indonesia,NaN,NaN,...,2010-04-11,2030-03-18,9998,Dablist,Sabine Drakeley,sdrakeleyrp@timesonline.co.uk,469-421-9241,PO Box 84909,Dallas,France
9998,9999,999,9999,Yetta,Huertas,26,pemesrq@wikimedia.org,Pakistan,70051,NaN,...,2021-12-28,2029-07-29,9999,Katz,Patric Emes,pemesrq@bizjournals.com,855-954-7325,Room 1617,Lingion,Jamaica
9999,10000,1000,10000,Bertram,Bohlje,20,jcordenrr@home.pl,Brazil,44570-000,NaN,...,2010-06-17,2026-04-23,10000,Realpoint,Jenny Corden,jcordenrr@moonfruit.com,686-812-9389,Suite 95,Plesná,Czech Republic

### Поля customer_postal_code, seller_postal_code, store_state имеют null значения

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 57 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     10000 non-null  int64
 1   external_id            10000 non-null  int64
 2   customer_inner_id      10000 non-null  int64
 3   customer_first_name    10000 non-null  str
 4   customer_last_name     10000 non-null  str
 5   customer_age           10000 non-null  int64
 6   customer_email         10000 non-null  str
 7   customer_country       10000 non-null  str
 8   customer_postal_code   4817 non-null   str
 9   customer_pet_inner_id  0 non-null      float64
 10  customer_pet_type      10000 non-null  str
 11  customer_pet_name      10000 non-null  str
 12  customer_pet_breed     10000 non-null  str
 13  seller_inner_id        10000 non-null  int64
 14  seller_first_name      10000 non-null  str
 15  seller_last_name       10000 non-null  str
 16  seller_email           10000 non-null  str
 17  seller_country         10000 non-null  str
 18  seller_postal_code     4732 non-null   str
 19  product_inner_id       10000 non-null  int64
 20  product_name           10000 non-null  str
 21  product_category       10000 non-null  str
 22  product_price          10000 non-null  float64
 23  product_quantity       10000 non-null  int64
 24  sale_date              10000 non-null  str
 25  sale_customer_id       10000 non-null  int64
 26  sale_seller_id         10000 non-null  int64
 27  sale_product_id        10000 non-null  int64
 28  sale_quantity          10000 non-null  int64
 29  sale_total_price       10000 non-null  float64
 30  store_inner_id         10000 non-null  int64
 31  store_name             10000 non-null  str
 32  store_location         10000 non-null  str
 33  store_city             10000 non-null  str
 34  store_state            1611 non-null   str
 35  store_country          10000 non-null  str
 36  store_phone            10000 non-null  str
 37  store_email            10000 non-null  str
 38  pet_category           10000 non-null  str
 39  product_weight         10000 non-null  float64
 40  product_color          10000 non-null  str
 41  product_size           10000 non-null  str
 42  product_brand          10000 non-null  str
 43  product_material       10000 non-null  str
 44  product_description    10000 non-null  str
 45  product_rating         10000 non-null  float64
 46  product_reviews        10000 non-null  int64
 47  product_release_date   10000 non-null  str
 48  product_expiry_date    10000 non-null  str
 49  supplier_inner_id      10000 non-null  int64
 50  supplier_name          10000 non-null  str
 51  supplier_contact       10000 non-null  str
 52  supplier_email         10000 non-null  str
 53  supplier_phone         10000 non-null  str
 54  supplier_address       10000 non-null  str
 55  supplier_city          10000 non-null  str
 56  supplier_country       10000 non-null  str
dtypes: float64(5), int64(14), str(38)
memory usage: 4.3 MB

In [4]:
data.nunique()

id                       10000
external_id               1000
customer_inner_id        10000
customer_first_name       5749
customer_last_name        9053
customer_age                68
customer_email           10000
customer_country           204
customer_postal_code      4036
customer_pet_inner_id        0
customer_pet_type            3
customer_pet_name         5846
customer_pet_breed           3
seller_inner_id          10000
seller_first_name         5787
seller_last_name          9025
seller_email             10000
seller_country             206
seller_postal_code        3980
product_inner_id         10000
product_name                 3
product_category             3
product_price             6262
product_quantity           100
sale_date                  364
sale_customer_id          1000
sale_seller_id            1000
sale_product_id           1000
sale_quantity               10
sale_total_price          9003
store_inner_id           10000
store_name                 383
store_location            4621
store_city                8227
store_state                194
store_country              200
store_phone              10000
store_email              10000
pet_category                 5
product_weight             500
product_color               19
product_size                 3
product_brand              383
product_material            11
product_description        147
product_rating              41
product_reviews           1001
product_release_date      4162
product_expiry_date       2829
supplier_inner_id        10000
supplier_name              383
supplier_contact         10000
supplier_email           10000
supplier_phone           10000
supplier_address          4619
supplier_city             8211
supplier_country           203
dtype: int64

In [5]:
data.describe()

,id,external_id,customer_inner_id,customer_age,customer_pet_inner_id,seller_inner_id,product_inner_id,product_price,product_quantity,sale_customer_id,sale_seller_id,sale_product_id,sale_quantity,sale_total_price,store_inner_id,product_weight,product_rating,product_reviews,supplier_inner_id
count,10000.00000,10000.000000,10000.00000,10000.000000,0.0,10000.00000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,500.500000,5000.50000,51.680300,NaN,5000.50000,5000.50000,50.816842,50.592200,500.500000,500.500000,500.500000,5.462300,252.985212,5000.50000,25.364210,3.008430,501.189500,5000.50000
std,2886.89568,288.689425,2886.89568,19.645607,NaN,2886.89568,2886.89568,28.310427,28.528307,288.689425,288.689425,288.689425,2.866845,141.691796,2886.89568,14.316088,1.160365,290.130449,2886.89568
min,1.00000,1.000000,1.00000,18.000000,NaN,1.00000,1.00000,1.990000,1.000000,1.000000,1.000000,1.000000,1.000000,10.070000,1.00000,0.100000,1.000000,0.000000,1.00000
25%,2500.75000,250.750000,2500.75000,35.000000,NaN,2500.75000,2500.75000,26.335000,26.000000,250.750000,250.750000,250.750000,3.000000,130.560000,2500.75000,13.000000,2.000000,251.000000,2500.75000
50%,5000.50000,500.500000,5000.50000,52.000000,NaN,5000.50000,5000.50000,50.515000,51.000000,500.500000,500.500000,500.500000,5.000000,250.900000,5000.50000,25.500000,3.000000,503.000000,5000.50000
75%,7500.25000,750.250000,7500.25000,69.000000,NaN,7500.25000,7500.25000,75.210000,75.000000,750.250000,750.250000,750.250000,8.000000,375.882500,7500.25000,37.700000,4.000000,753.000000,7500.25000
max,10000.00000,1000.000000,10000.00000,85.000000,NaN,10000.00000,10000.00000,99.980000,100.000000,1000.000000,1000.000000,1000.000000,10.000000,499.850000,10000.00000,50.000000,5.000000,1000.000000,10000.00000

### Поля sale_product_id, sale_customer_id, sale_seller_id имеют всего 1000 уникальных значений среди всех батчей и не равное 1000 количество уникальных значений в каждом батче, что указывает, что несколько продаж ссылаются на 1 продукт. Причем во всем датасете эти id от 1 до 1000, следовательно продажа ссылается на продукт внутри своего батча.

In [6]:
product_id_unique_in_batch = True
customer_id_unique_in_batch = True
seller_id_unique_in_batch = True

for i in range(0, 10000, 1000):
    product_id_unique_in_batch = product_id_unique_in_batch and data['sale_product_id'][i:i+1000].nunique() == 1000
    customer_id_unique_in_batch = customer_id_unique_in_batch and data['sale_customer_id'][i:i+1000].nunique() == 1000
    seller_id_unique_in_batch = seller_id_unique_in_batch and data['sale_seller_id'][i:i+1000].nunique() == 1000

(product_id_unique_in_batch, customer_id_unique_in_batch, seller_id_unique_in_batch)

(False, False, False)

### По уникальности полей customer_email, seller_email, supplier_email, store_email можно взять их как идентификаторы клиентов, продавцов, поставщиков и магазинов соответственно. При этом ясно, что данная таблица получена присоединением таблицы продаж к таблицам клиентов, продавцов, поставщиков и магазинов.

In [7]:
data[["customer_email", "seller_email", "supplier_email", "store_email"]].nunique()

customer_email    10000
seller_email      10000
supplier_email    10000
store_email       10000
dtype: int64

### Видно, что у каждого клиента есть 1 питомец, однако невозможно определить уникальный набор атрибутов для них, соответственно уникальным ключем для питомца будет сгенерированный id.

In [10]:
%%sql
SELECT mock_data.customer_pet_type, mock_data.customer_pet_name, mock_data.customer_pet_breed, COUNT(*)
FROM mock_data
GROUP BY mock_data.customer_pet_type, mock_data.customer_pet_name, mock_data.customer_pet_breed
ORDER BY count(*) DESC

,customer_pet_type,customer_pet_name,customer_pet_breed,pet_category,count
0,cat,Jennie,Labrador Retriever,Cats,3
1,cat,Isidore,Siamese,Dogs,2
2,bird,Marchall,Siamese,Fish,2
3,dog,Booth,Parakeet,Fish,2
4,cat,Daryl,Labrador Retriever,Cats,2
...,...,...,...,...,...
9845,dog,Edgardo,Siamese,Cats,1
9846,cat,Jo,Labrador Retriever,Fish,1
9847,cat,Shelagh,Siamese,Reptiles,1
9848,cat,Atlanta,Parakeet,Birds,1
9849,dog,Izaak,Parakeet,Fish,1

In [11]:
data[["customer_pet_type", "customer_pet_name", "customer_pet_breed"]].isna().sum()

customer_pet_type     0
customer_pet_name     0
customer_pet_breed    0
dtype: int64

# Analysis Result
1) Таким образом была составлена схема данных, которая включает в себя такие сущности как: продажа, продукт, клиент, продавец, поставщик, магазин и питомец.
2) Были добавлены автогенерируемые id для уникальных сущностей, а также определены связи между ними.
3) Были добавлены constraint'ы для обеспечения целостности данных, такие как NOT NULL и UNIQUE.
![DbSchema](schema.svg)

# Post Analysis

In [12]:
%%sql
SELECT count(*) FROM transactions_fact

   count
0  10000

In [13]:
%%sql
SELECT * FROM transactions_fact LIMIT 10

,id,customer_id,date,product_id,quantity,seller_id,store_id,total_price,pet_category,supplier_id
0,1,384,2021-11-07,384,1,384,384,453.20,Dogs,384
1,2,397,2021-02-02,397,6,397,397,475.26,Fish,397
2,3,402,2021-12-24,402,8,402,402,169.15,Birds,402
3,4,1262,2021-05-16,1262,4,1262,1262,211.24,Reptiles,1262
4,5,508,2021-05-16,508,3,508,508,83.79,Reptiles,508
5,6,515,2021-11-22,515,9,515,515,224.92,Reptiles,515
6,7,623,2021-05-14,623,6,623,623,423.43,Birds,623
7,8,3351,2021-03-18,3351,7,3351,3351,263.22,Birds,3351
8,9,788,2021-10-03,788,6,788,788,246.31,Fish,788
9,10,3861,2021-09-27,3861,3,3861,3861,175.37,Fish,3861

In [15]:
%%sql
SELECT COUNT(*) FROM products_dim

   count
0  10000

In [17]:
%%sql
SELECT * FROM products_dim LIMIT 10

,id,weight,color,size,brand,material,description,rating,reviews,release_date,expiry_date,category,name,price,quantity
0,384,18.1,Indigo,Medium,Katz,Steel,Phasellus in felis. Donec semper sapien a libe...,2.9,88,2010-11-18,2029-05-03,Cage,Bird Cage,50.00,14
1,397,19.9,Red,Medium,Youfeed,Vinyl,Phasellus in felis. Donec semper sapien a libe...,2.8,89,2015-05-15,2023-11-28,Cage,Bird Cage,24.14,36
2,402,33.9,Violet,Large,Riffpedia,Plastic,Phasellus in felis. Donec semper sapien a libe...,1.9,640,2017-12-07,2028-09-13,Cage,Cat Toy,31.61,39
3,1262,26.0,Maroon,Small,Thoughtstorm,Wood,Phasellus in felis. Donec semper sapien a libe...,4.9,387,2020-01-12,2026-01-07,Toy,Cat Toy,74.58,62
4,508,18.1,Yellow,Small,Thoughtbeat,Stone,In hac habitasse platea dictumst. Etiam faucib...,2.6,204,2019-05-30,2025-12-03,Toy,Bird Cage,62.62,59
5,515,40.9,Maroon,Small,Latz,Aluminum,Integer ac leo. Pellentesque ultrices mattis o...,1.9,869,2015-07-05,2023-06-21,Toy,Bird Cage,38.62,67
6,623,28.5,Green,Large,Eayo,Steel,Phasellus sit amet erat. Nulla tempus. Vivamus...,4.3,692,2015-02-25,2024-09-08,Cage,Dog Food,77.81,30
7,3351,8.4,Mauv,Medium,Quaxo,Aluminum,In congue. Etiam justo. Etiam pretium iaculis ...,2.8,407,2017-11-01,2027-07-05,Food,Bird Cage,19.44,64
8,788,22.1,Mauv,Large,Quatz,Vinyl,Duis bibendum. Morbi non quam nec dui luctus r...,4.7,550,2017-12-06,2027-09-08,Toy,Bird Cage,6.15,60
9,3861,28.0,Yellow,Small,Yodo,Granite,Duis bibendum. Morbi non quam nec dui luctus r...,3.3,591,2015-06-15,2030-01-21,Toy,Cat Toy,78.61,69

In [18]:
%%sql
SELECT COUNT(*) FROM customers_dim

   count
0  10000

In [20]:
%%sql
SELECT * FROM customers_dim LIMIT 10

,id,first_name,last_name,email,postal_code,country,age,pet_id
0,1,Barron,Rawlyns,bmassingham0@army.mil,NaN,China,61,1
1,2,Ham,Knowller,cscudder1@time.com,73-115,Poland,78,2
2,3,Farleigh,Langley,vhuxter2@fotki.com,56-160,Poland,71,3
3,4,Shae,Debling,bbullier3@bravesites.com,81700,Sri Lanka,28,4
4,5,Lay,Twatt,sedgar4@smugmug.com,NaN,Botswana,25,5
5,6,Frankie,Waycott,dgrindell5@usa.gov,666733,Russia,58,6
6,7,Boote,Ricart,kelies6@si.edu,11902,Dominican Republic,69,7
7,8,Mace,Parkman,tungaretti7@census.gov,58095,Mexico,22,8
8,9,Hobard,Rawnsley,mglason8@jugem.jp,NaN,China,74,9
9,10,Jorry,Cattenach,jpelerin9@cbsnews.com,34-146,Poland,46,10

In [22]:
%%sql
SELECT COUNT(*) FROM sellers_dim

   count
0  10000

In [23]:
%%sql
SELECT * FROM sellers_dim LIMIT 10

,id,first_name,last_name,email,postal_code,country
0,1,Bevan,Massingham,bmassingham0@answers.com,NaN,Indonesia
1,2,Candide,Scudder,cscudder1@xing.com,4015.0,Guatemala
2,3,Vinson,Huxter,vhuxter2@issuu.com,NaN,China
3,4,Bald,Bullier,bbullier3@imageshack.us,NaN,China
4,5,Sydelle,Edgar,sedgar4@sogou.com,NaN,China
5,6,Doria,Grindell,dgrindell5@slideshare.net,63136.0,United States
6,7,Kenny,Elies,kelies6@nba.com,NaN,Indonesia
7,8,Tabina,Ungaretti,tungaretti7@sphinn.com,NaN,Tajikistan
8,9,May,Glason,mglason8@dion.ne.jp,694230.0,Russia
9,10,Jorry,Pelerin,jpelerin9@nhs.uk,NaN,Indonesia

In [24]:
%%sql
SELECT COUNT(*) FROM suppliers_dim

   count
0  10000

In [26]:
%%sql
SELECT * FROM suppliers_dim LIMIT 10

,id,address,city,contact,country,email,name,phone
0,1,Suite 25,Kletek,Bevan Massingham,China,bmassingham0@unblog.fr,Tagcat,914-877-7062
1,2,18th Floor,Santa Cruz Balanyá,Candide Scudder,Poland,cscudder1@sbwire.com,Livetube,863-319-5653
2,3,Apt 96,Huangpu,Vinson Huxter,Samoa,vhuxter2@slate.com,Photobug,434-817-1275
3,4,12th Floor,Chengzhong,Bald Bullier,Indonesia,bbullier3@dot.gov,Janyx,515-756-7392
4,5,Suite 79,Lanxi,Sydelle Edgar,China,sedgar4@reverbnation.com,Lazz,861-980-8811
5,6,3rd Floor,Saint Louis,Doria Grindell,Russia,dgrindell5@1688.com,Izio,314-270-0484
6,7,PO Box 84390,Somorpenang,Kenny Elies,Mexico,kelies6@hao123.com,Fanoodle,627-887-5660
7,8,Room 922,Panjakent,Tabina Ungaretti,Russia,tungaretti7@shareasale.com,Thoughtblab,325-667-3782
8,9,3rd Floor,Leonidovo,May Glason,Philippines,mglason8@so-net.ne.jp,Dabvine,459-716-0328
9,10,Suite 34,Sukadami,Jorry Pelerin,Indonesia,jpelerin9@theguardian.com,Linktype,540-290-6958

In [28]:
%%sql
SELECT COUNT(*) FROM stores_dim

   count
0  10000

In [29]:
%%sql
SELECT * FROM stores_dim LIMIT 10

,id,city,country,email,location,name,phone,state
0,384,Aubenas,Brazil,adinsdalean@google.nl,PO Box 974,Mita,542-474-1367,B9
1,397,Herálec,Philippines,elindebergb0@wiley.com,Suite 68,Divanoodle,224-250-4444,NaN
2,402,Shayu,Guatemala,slowthianb5@joomla.org,Apt 147,Blogtags,323-396-0945,NaN
3,1262,Kamyzyak,Portugal,dland79@netscape.com,PO Box 70133,Kwinu,592-451-4052,NaN
4,508,Shayu,Azerbaijan,trenfielde3@google.com.hk,Room 1684,Rhynyx,720-645-9994,NaN
5,515,Mucurapo,China,dswinfonea@aol.com,Room 1294,Yodo,996-946-5282,NaN
6,623,Neuville,Madagascar,sstha@tripod.com,Apt 668,Midel,968-438-3971,QC
7,3351,Siliana,Sweden,kmeyrick9q@ucoz.com,Apt 462,Jayo,915-236-7347,NaN
8,788,Podivín,China,dkummerlowelv@blogger.com,Room 399,Youtags,285-610-0325,NaN
9,3861,Prévost,Italy,zmccurrynw@washington.edu,Suite 36,Skajo,115-153-5853,QC

In [31]:
%%sql
SELECT COUNT(*) FROM customer_pets_dim

   count
0  10000

In [32]:
%%sql
SELECT * FROM customer_pets_dim LIMIT 10

     id     name               breed type
0  1327     Cull            Parakeet  cat
1  1261     Hart  Labrador Retriever  dog
2  5203   Mattie  Labrador Retriever  dog
3  8355  Tatiana             Siamese  cat
4   473  Simonne  Labrador Retriever  dog
5  1850   Rennie             Siamese  dog
6  9860  Pacorro  Labrador Retriever  cat
7   187   Vernen            Parakeet  cat
8  1046     Lisa             Siamese  cat
9    54     Mora             Siamese  cat

In [33]:
%%sql
# SELECT * FROM transactions_fact

,id,customer_id,date,product_id,quantity,seller_id,store_id,total_price,pet_category,supplier_id
0,1,384,2021-11-07,384,1,384,384,453.20,Dogs,384
1,2,397,2021-02-02,397,6,397,397,475.26,Fish,397
2,3,402,2021-12-24,402,8,402,402,169.15,Birds,402
3,4,1262,2021-05-16,1262,4,1262,1262,211.24,Reptiles,1262
4,5,508,2021-05-16,508,3,508,508,83.79,Reptiles,508
...,...,...,...,...,...,...,...,...,...,...
9995,9996,9996,2021-04-07,9996,7,9996,9996,214.00,Dogs,9996
9996,9997,9997,2021-02-22,9997,4,9997,9997,495.11,Fish,9997
9997,9998,9998,2021-10-15,9998,10,9998,9998,267.09,Cats,9998
9998,9999,9999,2021-08-04,9999,4,9999,9999,334.71,Cats,9999
9999,10000,10000,2021-08-10,10000,9,10000,10000,307.93,Birds,10000